### ISSUE TITLE
A little suggestion for styles 

### ISSUE THREAD

**Issue by joelself** [joelself/github-badge#1]
Stolen from https://github.com/zenorocha/jquery-github/issues/42

The box looks strange on pages with CSS resets like this:

``` css
* { box-sizing: border-box; }
```

This is used quite often as far as I know.
So I suggest this to be added to base.css:

``` css
.github-box .github-box-download {
  // ...
  box-sizing: content-box;
}
```
